This is makeindex, version 2.15 [TeX Live 2014/dev] (kpathsea + Thai support).
Scanning style file ./rapport.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file rapport.acn....done (2 entries accepted, 0 rejected).
Sorting entries....done (2 comparisons).
Generating output file rapport.acr....done (9 lines written, 0 warnings).
Output written in rapport.acr.
Transcript written in rapport.alg.
